#!/bin/sh

RED=$'\033[0;31m'
NC=$'\033[0m'
GREEN=$'\033[92m'

while true; do
    read -p "All of your branches (${GREEN}except${NC} '${RED}main${NC}' ${GREEN}and${NC} '${RED}master${NC}') will be DELETED! ${RED}Are you sure about this? ${NC}(y/n): " yn
    case "$yn" in
        [Yy]*)
            git branch | grep -v 'main\|master' | grep -v ^* | xargs git branch -D
            break
            ;;
        [Nn]*)
            echo 'A smart decision!'
            exit
            ;;
        *)
            printf %s\\n "Please answer yes (y) or no (n)."
    esac
done
